server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    root: info # 默认的全局日志级别
    org.springframework.web: debug # web相关的日志级别
  #日志存放的路径
  file:
    path: /data/log
  logback:
    rolling-policy:
      max-file-size: 100MB
      max-history: 30
spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: 0
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
